# Generated by Django 4.1.6 on 2023-04-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicuser',
            old_name='identifier',
            new_name='username',
        ),
    ]
