# Generated by Django 4.1.6 on 2023-04-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0002_rename_identifier_basicuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='basicuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
